# Generated by Django 5.2.7 on 2025-11-29 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mailings",
            new_name="Mailing",
        ),
        migrations.RenameField(
            model_name="attempt",
            old_name="mailings",
            new_name="mailing",
        ),
    ]
