# Generated by Django 5.2.7 on 2025-11-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_message_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="recipient",
            new_name="recipients",
        ),
    ]
